version: '3.1'

services:

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
        - portainerdata:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  mongo: 
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db      

volumes:
  mongodata:
    driver: local
  portainerdata:
    driver: local